apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: ingress.k8s.com
    http:
      paths:
      - backend:
          serviceName: springboot
          servicePort: 80
