apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.metadata.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.metadata.namespace }}
spec:
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - image: {{ .Values.images.postgres }}
          name: postgres
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-key
                  key: POSTGRES_PASSWORD
            - name: PSQL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-key
                  key: PSQL_DB_USER
            - name: PSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-key
                  key: PSQL_DB_PASSWORD
            - name: PSQL_DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-key
                  key: PSQL_DB_DATABASE
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      imagePullSecrets:
      - name: container-registry-key
