apiVersion: v1
kind: Service
metadata:
  name: springboot-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: springboot
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springboot
spec:
  replicas: 1
  template:
    metadata:
      name: springboot
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: {{ .Values.images.spring_boot_app }}
        ports:
        - containerPort: 8080
          name: springboot
        imagePullPolicy: IfNotPresent
        env:
        - name: PSQL_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: spring-boot-config-map
              key: PSQL_DB_HOST
        - name: PSQL_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: spring-boot-config-map
              key: PSQL_DB_PORT
        - name: PSQL_DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-key
              key: PSQL_DB_USER
        - name: PSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-key
              key: PSQL_DB_PASSWORD
        - name: PSQL_DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-key
              key: PSQL_DB_DATABASE
      imagePullSecrets:
      - name: container-registry-key
