apiVersion: v1
kind: Service
metadata:
  name: springboot
  namespace: {{ .Values.metadata.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: springboot
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springboot
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      name: springboot
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: {{ .Values.images.springboot }}
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host
