version: '3.7'
services:
  postgres:
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      - "PSQL_DB_USER=psql_db_user"
      - "PSQL_DB_PASSWORD=x8TTj4hnfA8T4Fm"
      - "PSQL_DB_DATABASE=psql_db"
      - "POSTGRES_PASSWORD=H7n5GZTpAz5aN8a"
    build: './psql'
    image: postgres:latest
    container_name: postgres_container
    volumes: 
      - psql_db_volume:/var/lib/postgresql/data 
    networks:
      infranet:
        aliases:
          - 'postgres'
  spring-boot-rest:
    restart: 'always'
    depends_on:
      - "postgres"
    ports:
      - '8080:8080'
    environment:
      - "PSQL_DB_HOST=172.20.50.167"
      - "PSQL_DB_PORT=5432"
      - "PSQL_DB_USER=psql_db_user"
      - "PSQL_DB_PASSWORD=x8TTj4hnfA8T4Fm"
      - "PSQL_DB_NAME=psql_db"
    build: './app'
    image: springboot-rest-jpa:latest
    container_name: springboot_container
    networks: 
      infranet:
        aliases: 
          - 'springboot'
networks:
  infranet:
volumes: 
  psql_db_volume:
