version: '3.2'
services:
  postgres:
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      - "PSQL_DB_USER=psql_db_user"
      - "PSQL_DB_PASSWORD=x8TTj4hnfA8T4Fm"
      - "PSQL_DB_DATABASE=psql_db"
      - "POSTGRES_PASSWORD=H7n5GZTpAz5aN8a"
    build: './db'
    networks:
      infranet:
        aliases:
          - 'postgres'
networks:
  infranet:
