version: '3.2'
services:
  postgres:
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      - "FILLA_DB_USER=filla"
      - "FILLA_DB_PASSWORD=filla"
      - "FILLA_DB_DATABASE=filladb1"
      - "POSTGRES_PASSWORD=password"
    build: './db'
    networks:
      infranet:
        aliases:
          - 'postgres'

networks:
  infranet:
