apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  namespace: default
data:
  PSQL_DB_USER: psql_db_user
  PSQL_DB_PASSWORD: x8TTj4hnfA8T4Fm
  PSQL_DB_DATABASE: psql_db
  POSTGRES_PASSWORD: H7n5GZTpAz5aN8a
