apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: container-registry-key
  namespace: {{ .Values.metadata.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
